# Generated by Django 5.2.6 on 2025-09-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='contenido',
            new_name='cuerpo',
        ),
    ]
